using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum soundTypes
{
    RELEASE, SHOOT, ENEMY_ATTACK, ENEMY_DEAD, ISHAH, ENEMY_MOVE, OOH, OUCH, ENEMY_SPAWN, COIN, FORCE, GRAB, WALK, FIREPLACE, GARBAGE, TILE,
    FIGHT_BG, TAVERN_BG, TP, CANNON, EXPLOSION, POTION, SPLASH, TRAP_EXPLOSION, SPIKE, DEFENDERS, FIREWORKS, SCREAMS, TRUMPET
}
